# Generated by Django 4.0.2 on 2022-08-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(default='Sem categoria', related_name='posts', to='theblog.Category'),
        ),
    ]
